version: 2
jobs:
  build:
    working_directory: ~/some
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:6.11.1
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.   
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
  test:
    working_directory: ~/some
    docker:
      - image: circleci/node:6.11.1  
    steps:
      - checkout
      - run:
          name: mkdir artefacts
          command: mkdir -p /tmp/artefacts
      - run:
          name: npm install
          command: npm install
      - run:
          name: unit test
          command: node_modules/mocha/bin/mocha --reporter mocha-simple-html-reporter --reporter-options output=/tmp/artefacts/unit-tests.html
      - run:
          name: e2e test
          command:  ./node_modules/mocha/bin/mocha e2e --reporter mocha-simple-html-reporter --reporter-options output=/tmp/artefacts/e2e-tests.html
     - store_artifacts:
          path: /tmp/artefacts
      - store_artifacts:
          path: coverage
          prefix: coverage
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master